name: Sync Spotify Releases

on:
  workflow_dispatch:  # allows manual trigger
  schedule:
    - cron: "0 8 * * *"  # runs daily at 8am UTC

jobs:
  update-songs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Run Spotify Sync Script
        run: node scripts/fetchSpotify.js

      - name: Commit & Push changes
        run: |
          git config user.name "bazpod-bot"
          git config user.email "bot@bazpod.com"
          git add songs.js
          git commit -m "🔁 Auto-update songs from Spotify"
          git push
