name: Sync Spotify Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"  # daily at 8am UTC

jobs:
  update-songs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node-fetch
        run: npm install node-fetch@2

      - name: Run Spotify sync script
        run: node scripts/fetchSpotify.js

      - name: Commit & Push changes
        run: |
          git config --global user.name "bazpod-bot"
          git config --global user.email "boozethis@users.noreply.github.com"
          git pull origin main --rebase
          git add songs.js
          git commit -m "🔁 Auto-update songs from Spotify" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

